# Generated by Django 4.1.7 on 2023-06-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=100)),
                ("dob", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=3)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("phoneNumber", models.CharField(max_length=12)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("1", "Enquiry"),
                            ("2", "Place Order"),
                            ("3", "Return"),
                            ("4", "Feedback"),
                            ("5", "Queries"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "materials",
                    models.CharField(
                        choices=[
                            ("Notebook", "Notebook"),
                            ("Pen", "Pen"),
                            ("Exam Papers", "Exam Papers"),
                            ("Study Materials", "Study Materials"),
                            ("Books", "Books"),
                            ("Food", "Food"),
                            ("Gaming", "Gaming"),
                            ("Technology", "Technology"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "courses",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schoolapp.courses",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schoolapp.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="courses",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schoolapp.department"
            ),
        ),
    ]
